if(EXISTS "/home/fedor/Desktop/img_sound_proc/my_test[1]_tests.cmake")
  include("/home/fedor/Desktop/img_sound_proc/my_test[1]_tests.cmake")
else()
  add_test(my_test_NOT_BUILT my_test_NOT_BUILT)
endif()
